### default config ###
spring.profiles.active: development

server.port: 8081
spring.application.name: spring-boot
server.contextPath: /spring-boot

logging.config: classpath:config/logback.xml
logging.file: /Users/ypren/Desktop/log/spring-boot.log

param.folders: /one,/one

### development config ###
---

spring.profiles: development

logging.level: DEBUG

### test config ###
---

spring.profiles: test

logging.level: DEBUG

### production config ###
---
spring.profiles: production

logging.level: INFO




